### ISSUE TITLE
Tensorflow internal error: cuDNN launch failure

### ISSUE THREAD

**Issue by ssheorey** [intel-isl/Open3D-ML#292]
On some systems (e.g.: NVIDIA RTX 3070 laptop GPU, Ubuntu 20.04, CUDA 11.0, NVIDIA driver v460), running either training or testing with TensorFlow 2.4.1 may cause this error:

```
2021-06-02 13:10:33.815698: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2021-06-02 13:10:33.815735: W ./tensorflow/stream_executor/stream.h:2048] attempting to perform DNN operation using StreamExecutor without DNN support
```
or
`E   tensorflow.python.framework.errors_impl.InternalError: cuDNN launch failure : input shape ([1,5000,1,8]) [Op:FusedBatchNormV3]`

This may be related to the TensorFlow issue https://github.com/tensorflow/tensorflow/issues/45779
and can be resolved by asking TensorFlow to allocate GPU memory only as needed:
https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth

One way to do this is by setting the environment variable `TF_FORCE_GPU_ALLOW_GROWTH` to `true`. For example:

`TF_FORCE_GPU_ALLOW_GROWTH=true python -m pytest tests/test_models.py`

**Comment by kukuruza** [comment]
I faced this issue on Ubuntu 18.04, CUDA 11.0.3, cuDNN 8, Nvidia driver v470.103.01.

The solution above did NOT work.

However, after I upgraded to CUDA 11.4.3 with cuDNN 8, the issue disappeared.
